### PR TITLE
Add Firefox Support

### PR DESCRIPTION
**Pull request by indecisivemal**
Firefox now supports WebExtensions, more or less the same as Chrome and Opera. This seems to work with no significant changes.

Also added a makefile for building the xpi, but I don't know how to package for chrome.

To test:
Clone and run `make`
In Firefox, go to `about:debugging`, click "Load temporary add-on", select xpi.
Reload a page and the indicator should appear.

### CODE REVIEW

**Comment by indecisivemal** [comment]
Should have searched, #28 is related.

**Comment by pmarks-net** [comment]
I think Firefox's implementation of the extension API is currently too buggy to merge this.  I played with it for a bit on Firefox 53, and noticed the following problems:

- Most websites (e.g. www.kernel.org) show `?` until you reload the page.
- On www.reddit.com, 5 of the domains show `(no address)`.
- Right-clicking an IP address from the popup doesn't display the context menu.
- When the domain list exceeds the vertical height of the popup (e.g. on http://www.reddit.com or http://test-ipv6.com), this creates a horizontal scrollbar, when it should be vertical-only unless a very long name is present.

So we either need to convince Mozilla to fix the bugs, or add a bunch of Firefox-specific workarounds to IPvFoo.

**Comment by pmarks-net** [comment]
People keep asking for this, and "perfect is the enemy of good", so I think I'll publish it despite the flaws.

**Comment by andreicristianpetcu** [comment]
If you can't wait for the official one, I made an [unlisted signed build](https://github.com/andreicristianpetcu/ipvfoo/releases/download/v1.39.rc1/ipvfoo-1.39-an.fx.xpi) enjoy!

**Comment by pmarks-net** [comment]
https://addons.mozilla.org/en-US/firefox/addon/ipvfoo-pmarks went live this morning (the "ipvfoo" name was in use; did anyone on this bug take it?)

**Comment by indecisivemal** [comment]
Thanks for the pull, will poke at the problems if I get some time, but JS isn't by thing.

I haven't done anything with AMO.

**Comment by andreicristianpetcu** [comment]
Nice..... I will take down myne from GH. :)

**Comment by pmarks-net** [comment]
I'm gathering the Firefox bugs in https://github.com/pmarks-net/ipvfoo/issues/32

**Comment by rotanid** [comment]
thanks for porting this to firefox, i replaced IPvFox with your addon

**Pull request merged**
